// lit-hello-world/lit-hello-world.js
import {LitElement, html} from 'lit-element';

class HelloWorld extends LitElement {

    constructor(){
        super();
        this.name = "Lit sample widget";
        this.widgetAPI = (window).WS.widgetAPI();
    }

    static get properties(){
        return{
            name: { type: String },
        };
    }

    sendNotification() {
        this.widgetAPI.sendNotification('Hello World!', 'info');
      }

    render(){
        return html`
            <head>
                <link rel='stylesheet' href='assets/css/neo.min.css'>
            </head>
            <div class="neo-widget__content">
            <div class="neo-widget__header">
            <div class="neo-widget__header-left">
              <p>Lit Element</p>
            </div>
          </div>
            <div class="neo-widget__body">
                <div class="container">
                <h3><b>Sample widget demonstrating notification api methods</b></h3>
                <button class='neo-btn neo-btn-primary neo-btn-primary--primary' @click="${this.sendNotification}">Send Notification</button>
                </div>
                </div>
            </div>
        `;
    }
    }
    
customElements.define('lit-hello-world', HelloWorld);

// react-hello-world/src/HelloWorld.tsx
import React from 'react';
declare const window: any;

export default class HelloWorld extends React.Component {
  widgetAPI = (window).WS.widgetAPI();

  constructor (props: {} | Readonly<{}>){
    super(props);
    this.sendNotification = this.sendNotification.bind(this);
  }

  sendNotification() {
    this.widgetAPI.sendNotification('Hello World!', 'info');
  }

  render() {
    return (<div className="neo-widget__content">
      <div className="neo-widget__header">
      <div className="neo-widget__header-left">
        <span className="neo-icon-agents"></span>
        <p>React Web Component</p>
      </div>
    </div>
      <div className="neo-widget__body">
          <div className="container">
            <h3><b>Sample widget demonstrating notification api methods</b></h3>
            <button className='neo-btn neo-btn-primary neo-btn-primary--primary' onClick={this.sendNotification}>Send Notification</button>
          </div>
          </div>
      </div>
      );
    }
  }
